// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_G06.Data;

#nullable disable

namespace ProjectG06.Migrations
{
    [DbContext(typeof(UniProfileDbContext))]
    [Migration("20221213135623_AddUniProfileModelToDatabase")]
    partial class AddUniProfileModelToDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project_G06.Models.UniProfileModel", b =>
                {
                    b.Property<int>("Uni_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uni_ID"));

                    b.Property<byte?>("U_Picture")
                        .HasColumnType("tinyint");

                    b.Property<string>("Uni_Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Uni_Faculty_ID")
                        .HasColumnType("int");

                    b.Property<string>("Uni_FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uni_ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uni_ID");

                    b.HasIndex("Uni_Faculty_ID");

                    b.ToTable("UniProfileModels");
                });

            modelBuilder.Entity("Project_G06.Models.Uni_FacultyModel", b =>
                {
                    b.Property<int>("Uni_Faculty_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uni_Faculty_ID"));

                    b.Property<string>("Faculty_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uni_Faculty_ID");

                    b.ToTable("UnifacultyModels");
                });

            modelBuilder.Entity("Project_G06.Models.UniProfileModel", b =>
                {
                    b.HasOne("Project_G06.Models.Uni_FacultyModel", "UnifacultyModels")
                        .WithMany()
                        .HasForeignKey("Uni_Faculty_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnifacultyModels");
                });
#pragma warning restore 612, 618
        }
    }
}
