// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_G06.Data;

#nullable disable

namespace ProjectG06.Migrations
{
    [DbContext(typeof(UniProfileDbContext))]
    [Migration("20221213100023_AddUniProfileModelToDatabase")]
    partial class AddUniProfileModelToDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project_G06.Models.UniProfileModel", b =>
                {
                    b.Property<int>("Uni_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uni_ID"));

                    b.Property<byte?>("U_Picture")
                        .HasColumnType("tinyint");

                    b.Property<string>("Uni_Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Uni_FacultyID")
                        .HasColumnType("int");

                    b.Property<string>("Uni_FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uni_ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uni_ID");

                    b.ToTable("uniDashModels");
                });
#pragma warning restore 612, 618
        }
    }
}
